package chatRelay;

public enum actionType {
	LOGIN, SEND_MESSAGE, LOGOUT, // Added
    GET_ALL_CHATS, GET_ALL_USERS, GET_ALL_MESSAGES, CREATE_CHAT, 
    NEW_MESSAGE_BROADCAST, NEW_CHAT_BROADCAST, NEW_USER_BROADCAST, 
    SUCCESS, ERROR, UPDATED_USER_BROADCAST,
    CREATE_USER, ENABLE_USER, DISABLE_USER,
}
