package chatRelay;

public enum actionType {
	LOGIN, SEND_MESSAGE, LOGOUT, // Added
    GET_ALL_CHATS, GET_ALL_USERS, GET_ALL_MESSAGES, 
    CREATE_CHAT, 
    SUCCESS, ERROR, 
    CREATE_USER, ENABLE_USER, DISABLE_USER,
}
