package chatRelay;

public enum actionType {
	LOGIN, SEND_MESSAGE, LOGOUT,
    GET_ALL_CHATS, GET_ALL_USERS, CREATE_CHAT, GET_ALL_MESSAGES, 
    SUCCESS, ERROR, 
    CREATE_USER, ENABLE_USER, DISABLE_USER
}
